name: Greate User
#on: [push]
on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Greet the user
        run: echo "Hello, ${{ github.actor }}!"
      - name: Bye User
        run: echo "Bye, ${{ github.actor }}!"
